/**
 * App.jsx - InSight Hold Melt Dashboard
 *
 * Main dashboard component for visualizing PERC registration hold placement
 * and clearance patterns across academic years at Champlain College.
 *
 * ARCHITECTURE OVERVIEW:
 *   - Raw hold records are embedded as JSON (generated by scripts/build-data.py)
 *   - All melt-curve computation happens at runtime via computeAll()
 *   - The "delay" setting shifts end dates forward to account for backdating
 *   - All class standings (FY, SO, JR, SR, ALUM) included in melt curves
 *   - Class breakdown (FY/SO/JR) only used for current cohort where data is accurate
 *   - Hold recurrence tracked via student IDs across restriction codes
 *   - Prior-year average recalculates reactively when cohort toggles change
 *   - Date math uses native JavaScript Date objects (handles leap years)
 *
 * DATA FLOW:
 *   CSV (PERC export) -> build-data.py -> holds.json -> RAW_HOLDS -> computeAll()
 *   -> cohorts{} with melt curves -> Recharts visualization
 *
 * KEY SETTINGS:
 *   - Hold Release Delay: Compensates for the practice of backdating hold
 *     removal by N days. Default is 1 (a hold logged as removed on March 27
 *     was actually released on March 28).
 *   - Font Size: Scales all text proportionally (0.85x / 1.0x / 1.15x)
 */

import { useState, useMemo, useCallback, useRef, useEffect } from "react";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  BarChart, Bar, ReferenceLine, Area, AreaChart, ComposedChart
} from "recharts";


// ═══════════════════════════════════════════════════════════════════════
// RAW DATA
// Imported from src/data/holds.json, generated by scripts/build-data.py.
// Workflow: drop CSV in data/ -> npm run build-data -> Vite hot-reloads.
// Each record: { r: restriction code, s: start date, e: end date, c: class }
// Empty "e" means the hold is still active (student hasn't cleared).
// ═══════════════════════════════════════════════════════════════════════
import holdsData from "./data/holds.json";
const RAW_HOLDS = holdsData.holds;

/**
 * Maps restriction codes to academic year display labels.
 * Add new entries here as new hold cycles begin.
 */
const YEAR_LABELS = {
  "INS21": "20-21",
  "INS23": "22-23",
  "INS24": "23-24",
  "INS25": "24-25",
  "INS26": "25-26",
};


// ═══════════════════════════════════════════════════════════════════════
// CONFIGURATION
// ═══════════════════════════════════════════════════════════════════════

/** Display order for cohorts in charts and toggles (newest first) */
const COHORT_ORDER = ["INS26", "INS25", "INS24", "INS23", "INS21"];

/** Cohorts included in the "prior year average" calculation (excludes current) */
const PRIOR_COHORTS = ["INS25", "INS24", "INS23", "INS21"];

/** The current active cohort - gets special treatment (slider, snapshots, daily clearance) */
const CURRENT_COHORT = "INS26";

/** Maximum number of days to compute for the melt overlay */
const MAX_DAY = 180;

/** Day range presets for the melt chart x-axis zoom */
const DAY_RANGE_OPTIONS = [15, 30, 60, 90, 120, 180];

/** Color assigned to each cohort line in the melt overlay */
const COHORT_COLORS = {
  INS26: "#F2A900",  // Champlain Gold (highlighted as current year)
  INS25: "#5BA4CF",  // Blue
  INS24: "#6FCF97",  // Green
  INS23: "#E8805A",  // Orange
  INS21: "#A78BDA",  // Purple
};

/** Class standing colors for the snapshot stacked charts - dark theme */
const CLASS_COLORS_D = { FY: "#F2A900", SO: "#5BA4CF", JR: "#6FCF97" };

/** Class standing colors for the snapshot stacked charts - light theme */
const CLASS_COLORS_L = { FY: "#C98A00", SO: "#2E7AAD", JR: "#3BA56E" };

/**
 * Hold recurrence colors - escalating warmth to signal repeat holds.
 * Used in the Hold Recurrence section to distinguish 1st/2nd/3rd holds.
 */
const RECURRENCE_COLORS = {
  1: "#5BA4CF",  // Blue - first time through
  2: "#E8A84C",  // Amber - second hold
  3: "#E05A4E",  // Red - third consecutive hold
};

/** Font size multipliers for the settings panel */
const FONT_SCALES = { sm: 0.85, md: 1.0, lg: 1.15 };

/**
 * Theme definitions for dark and light modes.
 * Dark mode uses Champlain navy tones; light mode uses neutral grays.
 * Each theme provides colors for: backgrounds, text hierarchy, accents,
 * chart elements, and interactive controls.
 */
const themes = {
  dark: {
    bg: "#0B1A2E",           // Page background
    surface: "#122340",       // Card/panel background
    surfaceAlt: "#19305A",    // Alternate surface (toggles, inputs)
    border: "#1E3A68",        // Borders and dividers
    text: "#E8ECF2",          // Primary text
    textMuted: "#8899B3",     // Secondary text (labels, captions)
    textDim: "#546B8A",       // Tertiary text (de-emphasized)
    accent: "#F2A900",        // Champlain Gold - primary accent
    gridColor: "#1E3A68",     // Chart gridlines
    tooltipBg: "#19305A",     // Tooltip background
    cardHl: "rgba(242,169,0,0.08)",  // Highlighted card background
    sliderTrack: "#1E3A68",   // Range slider unfilled track
    avgBand: "rgba(255,255,255,0.06)", // Prior-year range band fill
    avgLine: "#8899B3",       // Prior-year average line
    sparkBar: "#6FCF97",      // Daily clearance bar color
    settingsBg: "#0D1F38",    // Settings panel background
    pillText: "#0B1A2E",      // Text on active pill buttons (dark on gold)
    red: "#E05A4E",           // Champlain Red - used for Total card
  },
  light: {
    bg: "#F4F6FA",
    surface: "#FFFFFF",
    surfaceAlt: "#EEF1F6",
    border: "#D4DAE3",
    text: "#1A2940",
    textMuted: "#5A6B82",
    textDim: "#8899AA",
    accent: "#C98A00",
    gridColor: "#E2E6ED",
    tooltipBg: "#FFFFFF",
    cardHl: "rgba(201,138,0,0.06)",
    sliderTrack: "#D4DAE3",
    avgBand: "rgba(0,0,0,0.04)",
    avgLine: "#5A6B82",
    sparkBar: "#3BA56E",
    settingsBg: "#E8ECF2",
    pillText: "#1A2940",
    red: "#B8352E",
  },
};


// ═══════════════════════════════════════════════════════════════════════
// DATE UTILITIES
// All date arithmetic uses native JavaScript Date objects, which handle
// leap years, month boundaries, and DST transitions correctly.
// We avoid manual day-of-year math to prevent Feb 29 edge cases.
// ═══════════════════════════════════════════════════════════════════════

/** Parse a "YYYY-MM-DD" string into a Date object (noon local time to avoid DST issues) */
function parseDate(s) {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}

/** Return a new Date that is `n` days after Date `d` */
function addDays(d, n) {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
}

/** Return the number of whole days between Date `a` and Date `b` */
function daysBetween(a, b) {
  return Math.round((b - a) / 86400000);
}

/** Format a Date as "Mar 1" style short display */
function fmtShort(d) {
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

/** Format a Date as "Sat, Mar 1, 2026" style long display */
function fmtLong(d) {
  return d.toLocaleDateString("en-US", {
    weekday: "short", month: "short", day: "numeric", year: "numeric"
  });
}

/** Convenience: parse a date string then format it short */
function fmtShortStr(s) {
  return fmtShort(parseDate(s));
}


// ═══════════════════════════════════════════════════════════════════════
// RUNTIME COMPUTATION
// This function processes raw hold records into melt curves, snapshots,
// and daily clearance data. It recalculates whenever the delay setting
// changes, since delay affects when holds are considered "released".
// ═══════════════════════════════════════════════════════════════════════

/**
 * Core computation engine. Takes raw hold records and a delay value,
 * returns everything the charts need.
 *
 * @param {Array} holds - Raw hold records [{r, s, e, c}, ...]
 * @param {number} delay - Days to add to logged end dates (backdating offset)
 * @returns {{ cohorts: Object, dailyClearance: Array }}
 */
function computeAll(holds, delay) {
  // ── Step 1: Group holds by restriction code ──
  const groups = {};
  for (const h of holds) {
    if (!groups[h.r]) groups[h.r] = [];
    groups[h.r].push(h);
  }

  const cohorts = {};
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  for (const [code, recs] of Object.entries(groups)) {

    // ── Step 2: Find the primary (bulk) placement date ──
    // Most holds in a code share the same start date (the bulk placement).
    // A few may have different dates (e.g., INS23 has one outlier).
    // We use the most common start date as the baseline for the x-axis.
    const startCounts = {};
    for (const r of recs) { startCounts[r.s] = (startCounts[r.s] || 0) + 1; }
    const primaryStart = Object.entries(startCounts).sort((a, b) => b[1] - a[1])[0][0];
    const startDate = parseDate(primaryStart);
    const total = recs.length;

    // ── Step 3: Pre-parse all dates for this cohort (performance) ──
    // Avoids re-parsing date strings on every iteration of the inner loop.
    const parsed = recs.map(h => ({
      start: parseDate(h.s),
      end: h.e ? addDays(parseDate(h.e), delay) : null,  // Apply delay here
      cls: h.c,
      hasEnd: !!h.e,
    }));

    // ── Step 4: Determine how many days to compute ──
    // For the current cohort, compute up to today.
    // For prior cohorts, compute the full MAX_DAY window.
    let endDay = MAX_DAY;
    if (code === CURRENT_COHORT) {
      endDay = Math.max(daysBetween(startDate, today), 1);
    }

    // ── Step 5: Build the melt curve day by day ──
    const curve = [];
    // classCurve provides FY/SO/JR breakdown (only for current cohort)
    const classCurve = code === CURRENT_COHORT ? [] : null;
    let daysTo50 = null;
    let daysTo25 = null;

    for (let d = 0; d <= Math.min(endDay, MAX_DAY); d++) {
      const currentDate = addDays(startDate, d);
      let remaining = 0;
      const byClass = { FY: 0, SO: 0, JR: 0 };

      for (const h of parsed) {
        // Skip holds not yet placed (handles rare multi-date placements)
        if (currentDate < h.start) continue;

        if (h.end) {
          // Hold has been released. It's "remaining" if we haven't reached
          // the actual end date (logged date + delay).
          if (currentDate < h.end) {
            remaining++;
            if (byClass[h.cls] !== undefined) byClass[h.cls]++;
          }
        } else {
          // No end date = hold is still active
          remaining++;
          if (byClass[h.cls] !== undefined) byClass[h.cls]++;
        }
      }

      // Calculate percentage of original holds still remaining
      const pct = Math.round(remaining / total * 1000) / 10;
      curve.push({ day: d, remaining, pct });

      // Store class-level detail for the snapshot view (current cohort only)
      if (classCurve) {
        classCurve.push({
          day: d,
          date: currentDate,
          FY: byClass.FY,
          SO: byClass.SO,
          JR: byClass.JR,
          total: remaining,
        });
      }

      // Track when the cohort first crosses 50% and 25% remaining
      if (daysTo50 === null && pct <= 50) daysTo50 = d;
      if (daysTo25 === null && pct <= 25) daysTo25 = d;
    }

    cohorts[code] = {
      label: YEAR_LABELS[code] || code,
      startDate: primaryStart,
      total,
      stillActive: recs.filter(r => !r.e).length,
      curve,
      classCurve,
      daysTo50,
      daysTo25,
      endDay,
    };
  }

  // ── Step 6: Compute daily clearance for the current cohort ──
  // Shows how many holds were cleared each day, broken down by class.
  // Used by the Daily Clearance bar chart.
  const cc = cohorts[CURRENT_COHORT];
  const dailyClearance = cc?.classCurve ? cc.classCurve.map((pt, i) => ({
    day: pt.day,
    date: pt.date,
    // Total cleared = previous day's remaining minus today's remaining
    cleared: i > 0 ? cc.classCurve[i - 1].total - pt.total : 0,
    // Per-class cleared (clamped to 0 to avoid negative from rounding)
    FY: i > 0 ? Math.max(0, cc.classCurve[i - 1].FY - pt.FY) : 0,
    SO: i > 0 ? Math.max(0, cc.classCurve[i - 1].SO - pt.SO) : 0,
    JR: i > 0 ? Math.max(0, cc.classCurve[i - 1].JR - pt.JR) : 0,
    // Remaining counts for tooltip context
    remTotal: pt.total,
    remFY: pt.FY,
    remSO: pt.SO,
    remJR: pt.JR,
  })) : [];

  return { cohorts, dailyClearance };
}


// ═══════════════════════════════════════════════════════════════════════
// SETTINGS PANEL
// Slide-out panel from the right edge. Contains font size selector and
// hold release delay stepper. The delay directly affects computation
// (all curves recalculate when it changes).
// ═══════════════════════════════════════════════════════════════════════

function SettingsPanel({ settings, onChange, theme, open, onClose, fs }) {
  if (!open) return null;
  const s = (base) => Math.round(base * fs);

  return (
    <>
      {/* Backdrop overlay */}
      <div onClick={onClose} style={{
        position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", zIndex: 998,
      }} />

      {/* Panel */}
      <div style={{
        position: "fixed", top: 0, right: 0, bottom: 0, width: 320, maxWidth: "90vw",
        background: theme.settingsBg, borderLeft: `1px solid ${theme.border}`,
        zIndex: 999, padding: 24, overflowY: "auto",
        boxShadow: "-8px 0 32px rgba(0,0,0,0.3)",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }}>
          <h3 style={{ fontSize: s(17), fontWeight: 700, color: theme.text }}>Settings</h3>
          <button onClick={onClose} style={{
            background: "none", border: "none", color: theme.textMuted,
            fontSize: 22, cursor: "pointer", padding: "4px 8px",
          }}>✕</button>
        </div>

        {/* ── Font Size Selector ── */}
        <div style={{ marginBottom: 28 }}>
          <label style={{
            display: "block", fontSize: s(12), fontWeight: 600, color: theme.textMuted,
            textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10,
          }}>Font Size</label>
          <div style={{ display: "flex", gap: 6 }}>
            {[
              { val: "sm", label: "Small" },
              { val: "md", label: "Medium" },
              { val: "lg", label: "Large" },
            ].map(o => (
              <button key={o.val}
                onClick={() => onChange({ ...settings, fontSize: o.val })}
                style={{
                  flex: 1, padding: "8px 0", borderRadius: 8,
                  border: `1.5px solid ${settings.fontSize === o.val ? theme.accent : theme.border}`,
                  background: settings.fontSize === o.val ? `${theme.accent}18` : "transparent",
                  color: settings.fontSize === o.val ? theme.accent : theme.textMuted,
                  cursor: "pointer", fontSize: s(12), fontWeight: 600,
                }}>{o.label}</button>
            ))}
          </div>
        </div>

        {/* ── Hold Release Delay Stepper ── */}
        <div style={{ marginBottom: 28 }}>
          <label style={{
            display: "block", fontSize: s(12), fontWeight: 600, color: theme.textMuted,
            textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 6,
          }}>Hold Release Delay (days)</label>
          <p style={{ fontSize: s(11), color: theme.textDim, marginBottom: 10, lineHeight: 1.5 }}>
            Accounts for backdating when lifting holds. A delay of 1 means a hold
            logged as removed on March 27 was actually released on March 28.
          </p>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <button
              onClick={() => onChange({ ...settings, delay: Math.max(0, settings.delay - 1) })}
              style={{
                width: 36, height: 36, borderRadius: 8, border: `1px solid ${theme.border}`,
                background: theme.surfaceAlt, color: theme.text, fontSize: 18, cursor: "pointer",
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>-</button>
            <div style={{
              flex: 1, textAlign: "center", fontSize: s(24), fontWeight: 700,
              color: theme.accent, fontFamily: "'DM Mono',monospace",
            }}>{settings.delay}</div>
            <button
              onClick={() => onChange({ ...settings, delay: settings.delay + 1 })}
              style={{
                width: 36, height: 36, borderRadius: 8, border: `1px solid ${theme.border}`,
                background: theme.surfaceAlt, color: theme.text, fontSize: 18, cursor: "pointer",
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>+</button>
          </div>
          <div style={{ textAlign: "center", fontSize: s(11), color: theme.textDim, marginTop: 6 }}>
            {settings.delay === 0 ? "No adjustment (use logged dates as-is)" :
             settings.delay === 1 ? "End dates shifted forward 1 day" :
             `End dates shifted forward ${settings.delay} days`}
          </div>
        </div>

        {/* ── Pipeline Reminder ── */}
        <div style={{
          padding: 14, borderRadius: 8, background: `${theme.accent}08`,
          border: `1px solid ${theme.accent}20`, fontSize: s(11),
          color: theme.textMuted, lineHeight: 1.6,
        }}>
          <strong style={{ color: theme.accent }}>Pipeline note:</strong> To update
          data, place a fresh CSV export in the{" "}
          <code style={{ background: theme.surfaceAlt, padding: "1px 5px", borderRadius: 3 }}>data/</code>{" "}
          folder and run{" "}
          <code style={{ background: theme.surfaceAlt, padding: "1px 5px", borderRadius: 3 }}>
            python3 scripts/build-data.py
          </code>
        </div>
      </div>
    </>
  );
}


// ═══════════════════════════════════════════════════════════════════════
// REUSABLE UI COMPONENTS
// ═══════════════════════════════════════════════════════════════════════

/**
 * Pill - A segmented toggle control for switching between chart modes.
 * Used for %/# toggle, Area/Bars toggle, and daily clearance view modes.
 */
function Pill({ options, value, onChange, theme, fs }) {
  return (
    <div style={{ display: "flex", gap: 3, background: theme.surfaceAlt, borderRadius: 8, padding: 3 }}>
      {options.map(o => (
        <button key={String(o.val)} onClick={() => onChange(o.val)} style={{
          padding: "5px 14px", borderRadius: 6, border: "none", cursor: "pointer",
          fontSize: Math.round(12 * fs), fontWeight: 600, transition: "all 0.15s",
          background: value === o.val ? theme.accent : "transparent",
          color: value === o.val ? theme.pillText : theme.textMuted,
        }}>{o.label}</button>
      ))}
    </div>
  );
}

/**
 * StatCard - Summary metric display card.
 * Shows a label, large value, and optional subtitle.
 * The `highlight` prop applies accent coloring (used for "Remaining" card).
 */
function StatCard({ label, value, sub, theme, highlight, fs }) {
  return (
    <div style={{
      background: highlight ? theme.cardHl : theme.surface,
      border: `1px solid ${highlight ? theme.accent : theme.border}`,
      borderRadius: 10, padding: "16px 20px", flex: 1, minWidth: 130,
    }}>
      <div style={{
        fontSize: Math.round(12 * fs), fontWeight: 600, color: theme.textMuted,
        textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4,
      }}>{label}</div>
      <div style={{
        fontSize: Math.round(28 * fs), fontWeight: 700,
        color: highlight ? theme.accent : theme.text, lineHeight: 1.1,
      }}>{value}</div>
      {sub && <div style={{
        fontSize: Math.round(12 * fs), color: theme.textDim, marginTop: 4,
      }}>{sub}</div>}
    </div>
  );
}

/**
 * CohortToggle - Clickable pill for enabling/disabling a cohort on the melt chart.
 * Shows the cohort label, hold count, and a colored indicator dot.
 * Current cohort gets bold text and a glowing dot.
 */
function CohortToggle({ code, enabled, onToggle, theme, total, fs }) {
  const color = COHORT_COLORS[code];
  const isCur = code === CURRENT_COHORT;
  const label = (YEAR_LABELS[code] || code) + (isCur ? " (current)" : "");
  return (
    <button onClick={() => onToggle(code)} style={{
      display: "inline-flex", alignItems: "center", gap: 7,
      padding: "5px 12px", borderRadius: 20,
      border: `1.5px solid ${enabled ? color : theme.border}`,
      background: enabled ? `${color}18` : "transparent",
      cursor: "pointer", transition: "all 0.15s", opacity: enabled ? 1 : 0.4,
    }}>
      <span style={{
        width: 9, height: 9, borderRadius: "50%",
        background: enabled ? color : theme.textDim,
        boxShadow: enabled && isCur ? `0 0 8px ${color}88` : "none",
      }} />
      <span style={{
        fontSize: Math.round(12 * fs), fontWeight: isCur ? 700 : 500,
        color: enabled ? theme.text : theme.textDim,
      }}>{label}</span>
      <span style={{ fontSize: Math.round(11 * fs), color: theme.textDim }}>({total})</span>
    </button>
  );
}


// ═══════════════════════════════════════════════════════════════════════
// TOOLTIP COMPONENTS
// Custom Recharts tooltip renderers for each chart type.
// ═══════════════════════════════════════════════════════════════════════

/** Shared base styles for all tooltips */
const ttBase = (t) => ({
  background: t.tooltipBg, border: `1px solid ${t.border}`, borderRadius: 8,
  padding: "10px 14px", fontSize: 12, boxShadow: "0 4px 16px rgba(0,0,0,0.25)",
});

/**
 * MeltTooltip - Tooltip for the Historical Melt Comparison chart.
 * Shows remaining holds for each visible cohort at the hovered day,
 * plus prior-year average stats when the avg overlay is enabled.
 */
function MeltTooltip({ active, payload, label, showPct, theme, showAvg, priorAvg }) {
  if (!active || !payload?.length) return null;
  const avgEntry = showAvg && showPct ? priorAvg.find(d => d.day === label) : null;
  return (
    <div style={{ ...ttBase(theme), maxWidth: 230 }}>
      <div style={{ fontWeight: 700, color: theme.text, marginBottom: 6 }}>Day {label}</div>
      {payload
        .filter(p => p.dataKey !== "avgRange" && p.dataKey !== "avg" && p.value != null)
        .map((p, i) => (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
            <span style={{ width: 8, height: 8, borderRadius: "50%", background: p.color || p.stroke }} />
            <span style={{ color: theme.textMuted }}>
              {(YEAR_LABELS[p.dataKey] || p.dataKey) + (p.dataKey === CURRENT_COHORT ? " (current)" : "")}:
            </span>
            <span style={{ fontWeight: 600, color: theme.text }}>
              {showPct ? `${p.value}%` : p.value}
            </span>
          </div>
        ))}
      {avgEntry && (
        <div style={{
          borderTop: `1px solid ${theme.border}`, marginTop: 4, paddingTop: 4,
          fontSize: 11, color: theme.textDim,
        }}>
          Prior avg: {avgEntry.avg}% · Range: {avgEntry.min}% – {avgEntry.max}%
        </div>
      )}
    </div>
  );
}

/**
 * SnapshotTooltip - Tooltip for the Hold Snapshot stacked area/bar chart.
 * Shows per-class breakdown and total for the hovered date.
 */
function SnapshotTooltip({ active, payload, label, theme }) {
  if (!active || !payload?.length) return null;
  const total = payload.reduce((s, p) => s + (p.value || 0), 0);
  return (
    <div style={ttBase(theme)}>
      <div style={{ fontWeight: 700, color: theme.text, marginBottom: 6 }}>{label}</div>
      {[...payload].reverse().map((p, i) => (
        <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
          <span style={{ width: 8, height: 8, borderRadius: 2, background: p.fill || p.stroke || p.color }} />
          <span style={{ color: theme.textMuted }}>{p.dataKey}:</span>
          <span style={{ fontWeight: 600, color: theme.text }}>{p.value}</span>
        </div>
      ))}
      <div style={{
        borderTop: `1px solid ${theme.border}`, marginTop: 4, paddingTop: 4,
        fontWeight: 700, color: theme.accent,
      }}>Total: {total}</div>
    </div>
  );
}

/**
 * ClearanceTooltip - Tooltip for the Daily Clearance chart.
 * Shows cleared count per visible class, plus remaining breakdown.
 * Adapts to whichever view mode (total, stacked, or single class) is active.
 */
function ClearanceTooltip({ active, payload, label, theme, clearanceData }) {
  if (!active || !payload?.length) return null;
  // Look up the full data row for the remaining count context
  const entry = clearanceData?.find(d => d.dateLabel === label);
  return (
    <div style={{ ...ttBase(theme), padding: "8px 12px" }}>
      <div style={{ fontWeight: 700, color: theme.text, marginBottom: 4 }}>{label}</div>
      {/* Show "No change" if all visible bars are zero */}
      {payload.filter(p => p.value > 0).length === 0 && (
        <div style={{ color: theme.textDim }}>No change</div>
      )}
      {[...payload].reverse().filter(p => p.value > 0).map((p, i) => (
        <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
          <span style={{ width: 8, height: 8, borderRadius: 2, background: p.fill || p.color }} />
          <span style={{ color: theme.textMuted }}>
            {p.dataKey === "cleared" ? "Total" : p.dataKey}:
          </span>
          <span style={{ fontWeight: 600, color: theme.text }}>{p.value} cleared</span>
        </div>
      ))}
      {entry && (
        <div style={{
          color: theme.textDim, marginTop: 3, fontSize: 11,
          borderTop: `1px solid ${theme.border}`, paddingTop: 3,
        }}>
          {entry.remTotal} remaining ({entry.remFY} FY · {entry.remSO} SO · {entry.remJR} JR)
        </div>
      )}
    </div>
  );
}


// ═══════════════════════════════════════════════════════════════════════
// MAIN DASHBOARD COMPONENT
// ═══════════════════════════════════════════════════════════════════════

export default function HoldMeltDashboard() {
  // ── State ──
  const [dark, setDark] = useState(true);                    // Theme: dark (default) or light
  const [showPct, setShowPct] = useState(true);               // Melt chart: show % or absolute #
  const [showAvg, setShowAvg] = useState(true);               // Show prior-year average overlay
  const [sliderDay, setSliderDay] = useState(null);           // Snapshot slider position (null = latest)
  const [snapMode, setSnapMode] = useState("area");           // Snapshot chart: "area" or "bars"
  const [clearanceView, setClearanceView] = useState("total");// Daily clearance: total|stacked|FY|SO|JR
  const [enabledCohorts, setEnabledCohorts] = useState(       // Which cohorts are visible on melt chart
    Object.fromEntries(COHORT_ORDER.map(c => [c, true]))
  );
  const [playing, setPlaying] = useState(false);              // Is Play Melt animation running?
  const [settingsOpen, setSettingsOpen] = useState(false);    // Settings panel visibility
  const [dayRange, setDayRange] = useState(60);               // Melt chart x-axis range (days)
  const [showResolution, setShowResolution] = useState(false); // Show "last clearance" lines on melt chart
  const [settings, setSettings] = useState({                  // User-adjustable settings
    fontSize: "md",  // sm | md | lg
    delay: 1,        // Hold release delay in days
  });
  const timerRef = useRef(null);  // Ref for the Play Melt interval timer

  // ── Derived values ──
  const theme = dark ? themes.dark : themes.light;
  const classColors = dark ? CLASS_COLORS_D : CLASS_COLORS_L;
  const fs = FONT_SCALES[settings.fontSize] || 1;  // Current font scale multiplier
  const s = (base) => Math.round(base * fs);        // Helper to scale font sizes

  /** Toggle a cohort's visibility on the melt chart */
  const toggleCohort = useCallback(code => {
    setEnabledCohorts(prev => ({ ...prev, [code]: !prev[code] }));
  }, []);

  // ── Core computation (recalculates when delay changes) ──
  const computed = useMemo(
    () => computeAll(RAW_HOLDS, settings.delay),
    [settings.delay]
  );
  const { cohorts, dailyClearance } = computed;

  // ── Prior-year average (recalculates when cohort toggles change) ──
  // Only includes cohorts that are currently toggled ON, so the average
  // line and range band update dynamically as you enable/disable years.
  const priorAvg = useMemo(() => {
    const activePrior = PRIOR_COHORTS.filter(c => enabledCohorts[c] && cohorts[c]);
    if (activePrior.length === 0) return [];
    const avg = [];
    for (let d = 0; d <= MAX_DAY; d++) {
      const vals = activePrior
        .map(c => cohorts[c]?.curve.find(e => e.day === d)?.pct)
        .filter(v => v != null);
      if (vals.length > 0) {
        const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
        avg.push({
          day: d,
          avg: Math.round(mean * 10) / 10,
          min: Math.round(Math.min(...vals) * 10) / 10,
          max: Math.round(Math.max(...vals) * 10) / 10,
        });
      }
    }
    return avg;
  }, [cohorts, enabledCohorts]);

  // ── Resolution days (last clearance day per cohort) ──
  // For each cohort, finds the last day any hold was cleared (the curve stopped
  // decreasing). Used for the optional "last clearance" reference lines.
  // Cohorts with holds still clearing return null.
  const resolutionDays = useMemo(() => {
    const result = {};
    for (const code of COHORT_ORDER) {
      const curve = cohorts[code]?.curve;
      if (!curve || curve.length < 2) { result[code] = null; continue; }
      let lastDrop = null;
      for (let i = 1; i < curve.length; i++) {
        if (curve[i].remaining < curve[i - 1].remaining) lastDrop = curve[i].day;
      }
      result[code] = lastDrop;
    }
    return result;
  }, [cohorts]);

  // ── Current cohort snapshot data ──
  const curCohort = cohorts[CURRENT_COHORT];
  const maxSlider = curCohort ? curCohort.endDay : 0;
  const effectiveSlider = sliderDay === null ? maxSlider : Math.min(sliderDay, maxSlider);
  const snapshots = curCohort?.classCurve || [];
  const snap = snapshots[effectiveSlider]
    || snapshots[snapshots.length - 1]
    || { FY: 0, SO: 0, JR: 0, total: 0, date: new Date(), day: 0 };

  // Initialize slider to the latest day once data is ready
  useEffect(() => {
    if (sliderDay === null && maxSlider > 0) setSliderDay(maxSlider);
  }, [maxSlider]);

  const cleared = curCohort ? curCohort.total - snap.total : 0;
  const pctCleared = curCohort ? ((cleared / curCohort.total) * 100).toFixed(1) : "0";

  // ── Chart data transformations (memoized) ──

  // Melt overlay: one data point per day, with each cohort as a key
  const overlayData = useMemo(() => {
    const out = [];
    for (let d = 0; d <= MAX_DAY; d++) {
      const pt = { day: d };
      for (const code of COHORT_ORDER) {
        const e = cohorts[code]?.curve.find(x => x.day === d);
        if (e) pt[code] = showPct ? e.pct : e.remaining;
      }
      // Add prior-year average band data (percentage mode only)
      if (showPct) {
        const a = priorAvg.find(x => x.day === d);
        if (a) { pt.avg = a.avg; pt.avgRange = [a.min, a.max]; }
      }
      out.push(pt);
    }
    return out;
  }, [showPct, cohorts, priorAvg]);

  // Filter overlay data to the selected day range for rendering
  const visibleOverlayData = useMemo(() =>
    overlayData.filter(d => d.day <= dayRange),
  [overlayData, dayRange]);

  // Snapshot: formatted dates with class breakdown for stacked charts
  const snapChartData = useMemo(() =>
    snapshots.map(sn => ({
      date: fmtShort(sn.date), FY: sn.FY, SO: sn.SO, JR: sn.JR,
    })),
  [snapshots]);

  // Daily clearance: formatted dates with per-class clearance counts
  const clearanceChartData = useMemo(() =>
    dailyClearance.map(d => ({
      dateLabel: d.date ? fmtShort(d.date) : "",
      cleared: d.cleared, FY: d.FY, SO: d.SO, JR: d.JR,
      remTotal: d.remTotal, remFY: d.remFY, remSO: d.remSO, remJR: d.remJR,
    })),
  [dailyClearance]);

  // ── Hold recurrence computation ──
  // Groups students by ID across all restriction codes, then for the current
  // cohort, determines how many prior holds each student has had.
  // This answers: of INS26 students, how many are first-timers vs repeaters?
  const recurrenceData = useMemo(() => {
    // Step 1: Build a map of student ID -> set of restriction codes
    const studentCodes = {};
    for (const h of RAW_HOLDS) {
      if (!h.i) continue;  // skip records without student ID
      if (!studentCodes[h.i]) studentCodes[h.i] = new Set();
      studentCodes[h.i].add(h.r);
    }

    // Step 2: For current cohort students, determine hold count and clearance
    const currentHolds = RAW_HOLDS.filter(h => h.r === CURRENT_COHORT);
    const groups = { 1: { count: 0, cleared: 0 }, 2: { count: 0, cleared: 0 }, 3: { count: 0, cleared: 0 } };

    for (const h of currentHolds) {
      const totalHolds = studentCodes[h.i] ? studentCodes[h.i].size : 1;
      // Clamp to 3 (in case future data has 4+)
      const bucket = Math.min(totalHolds, 3);
      groups[bucket].count++;
      if (h.e) groups[bucket].cleared++;
    }

    const total = currentHolds.length;
    return { groups, total };
  }, []);  // RAW_HOLDS is a module-level constant, no deps needed

  // ── Play Melt animation ──
  // Steps the slider from current position to the latest day at 120ms intervals.
  // Supports play, pause, and resume.

  /** Start or resume the animation from the current slider position */
  const playAnimation = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    setPlaying(true);
    // If at the end (or very start with null), restart from 0
    const startFrom = (effectiveSlider >= maxSlider) ? 0 : effectiveSlider;
    if (startFrom === 0) setSliderDay(0);
    let f = startFrom;
    timerRef.current = setInterval(() => {
      f++;
      if (f >= maxSlider) {
        setSliderDay(maxSlider);
        setPlaying(false);
        clearInterval(timerRef.current);
        timerRef.current = null;
      } else {
        setSliderDay(f);
      }
    }, 120);
  }, [maxSlider, effectiveSlider]);

  /** Pause the animation, keeping the slider where it is */
  const pauseAnimation = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
    setPlaying(false);
  }, []);

  /** Whether the slider is mid-animation (paused between start and end) */
  const isPaused = !playing && effectiveSlider > 0 && effectiveSlider < maxSlider;

  // Clean up animation timer on unmount
  useEffect(() => () => {
    if (timerRef.current) clearInterval(timerRef.current);
  }, []);

  // ── Shared Recharts prop objects ──
  const gridProps = { stroke: theme.gridColor, strokeDasharray: "3 3" };
  const xAxisProps = { stroke: theme.textDim, fontSize: s(10), tickLine: false };
  const yAxisProps = { stroke: theme.textDim, fontSize: s(11), tickLine: false };


  // ═══════════════════════════════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════════════════════════════

  return (
    <div style={{
      background: theme.bg, color: theme.text, minHeight: "100vh",
      fontFamily: "'DM Sans','Segoe UI',system-ui,sans-serif",
      fontSize: s(14), transition: "background 0.3s, color 0.3s",
    }}>
      {/* Global styles (fonts, range input, chart grid opacity) */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        input[type=range] { -webkit-appearance: none; width: 100%; height: 6px; border-radius: 3px; outline: none; cursor: pointer; }
        input[type=range]::-webkit-slider-thumb { -webkit-appearance: none; width: 20px; height: 20px; border-radius: 50%; cursor: pointer; border: 2px solid; }
        .recharts-cartesian-grid-horizontal line,
        .recharts-cartesian-grid-vertical line { stroke-opacity: 0.4; }
      `}</style>

      {/* Settings slide-out panel */}
      <SettingsPanel
        settings={settings} onChange={setSettings} theme={theme}
        open={settingsOpen} onClose={() => setSettingsOpen(false)} fs={fs}
      />

      {/* ═══ HEADER ═══ */}
      <div style={{
        padding: "20px 28px", borderBottom: `1px solid ${theme.border}`,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        background: theme.surface,
      }}>
        <div>
          <div style={{ display: "flex", alignItems: "baseline", gap: 12, flexWrap: "wrap" }}>
            <h1 style={{ fontSize: s(22), fontWeight: 700, letterSpacing: "-0.02em" }}>
              InSight Hold Melt
            </h1>
            <span style={{
              fontSize: s(11), fontWeight: 600, color: theme.accent,
              background: `${theme.accent}18`, padding: "3px 10px",
              borderRadius: 12, letterSpacing: "0.04em",
            }}>PERC REGISTRATION HOLDS</span>
            {/* Show delay badge in header when delay differs from default */}
            {settings.delay !== 1 && (
              <span style={{
                fontSize: s(10), fontWeight: 600, color: theme.textMuted,
                background: theme.surfaceAlt, padding: "3px 8px", borderRadius: 8,
              }}>delay: {settings.delay}d</span>
            )}
          </div>
          <p style={{ fontSize: s(13), color: theme.textMuted, marginTop: 4 }}>
            Tracking hold placement and clearance across academic years. Class breakdown shown for current year only.
          </p>
        </div>
        <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
          <button onClick={() => setSettingsOpen(true)} style={{
            background: "none", border: "none", cursor: "pointer",
            fontSize: 20, padding: "6px 8px", borderRadius: 8, color: theme.textMuted,
          }} title="Settings">⚙️</button>
          <button onClick={() => setDark(!dark)} style={{
            background: "none", border: "none", cursor: "pointer",
            fontSize: 22, padding: "6px 8px", borderRadius: 8,
          }} title={dark ? "Light mode" : "Dark mode"}>
            {dark ? "☀️" : "🌙"}
          </button>
        </div>
      </div>

      <div style={{ padding: "24px 28px", maxWidth: 1200, margin: "0 auto" }}>

        {/* ═══ SUMMARY CARDS ═══ */}
        {/* Four key metrics for the current cohort, updated by the slider position */}
        <div style={{ display: "flex", gap: 14, marginBottom: 28, flexWrap: "wrap" }}>
          <StatCard
            label="Holds Placed" value={curCohort?.total || 0}
            sub={curCohort ? fmtShortStr(curCohort.startDate) + ", " + curCohort.startDate.slice(0, 4) : ""}
            theme={theme} fs={fs}
          />
          <StatCard
            label="Cleared" value={cleared}
            sub={snap.date ? `as of ${fmtShort(snap.date)}` : ""}
            theme={theme} fs={fs}
          />
          <StatCard
            label="Remaining" value={snap.total}
            sub={`${pctCleared}% cleared`}
            theme={theme} highlight fs={fs}
          />
          <StatCard
            label="Days Elapsed" value={effectiveSlider}
            sub={snap.date ? fmtLong(snap.date) : ""}
            theme={theme} fs={fs}
          />
        </div>

        {/* ═══ HISTORICAL MELT COMPARISON (Mansfield-style overlay) ═══ */}
        {/* Each academic year as a line on a shared "days since placement" x-axis.
            Inspired by the Mount Mansfield snow stake seasonal overlay chart.
            Prior-year average line + range band provides instant context. */}
        <div style={{
          background: theme.surface, border: `1px solid ${theme.border}`,
          borderRadius: 12, padding: "20px 24px", marginBottom: 24,
        }}>
          <div style={{
            display: "flex", alignItems: "center", justifyContent: "space-between",
            marginBottom: 16, flexWrap: "wrap", gap: 12,
          }}>
            <div>
              <h2 style={{ fontSize: s(16), fontWeight: 700 }}>Historical Melt Comparison</h2>
              <p style={{ fontSize: s(12), color: theme.textMuted, marginTop: 2 }}>
                How quickly do holds clear each year? Days since bulk placement on x-axis.
              </p>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              {/* Prior Average toggle (only visible in % mode) */}
              {showPct && (
                <button onClick={() => setShowAvg(!showAvg)} style={{
                  padding: "5px 12px", borderRadius: 6,
                  border: `1px solid ${showAvg ? theme.avgLine + "60" : theme.border}`,
                  background: showAvg ? `${theme.avgLine}15` : "transparent",
                  color: showAvg ? theme.text : theme.textDim,
                  cursor: "pointer", fontSize: s(12), fontWeight: 500,
                }}>{showAvg ? "▣" : "▢"} Prior Avg</button>
              )}
              {/* Resolution lines toggle */}
              <button onClick={() => setShowResolution(!showResolution)} style={{
                padding: "5px 12px", borderRadius: 6,
                border: `1px solid ${showResolution ? theme.accent + "60" : theme.border}`,
                background: showResolution ? `${theme.accent}15` : "transparent",
                color: showResolution ? theme.text : theme.textDim,
                cursor: "pointer", fontSize: s(12), fontWeight: 500,
              }}>{showResolution ? "▣" : "▢"} Last Clear</button>
              {/* Percentage / Absolute count toggle */}
              <Pill
                options={[{ val: true, label: "%" }, { val: false, label: "#" }]}
                value={showPct} onChange={setShowPct} theme={theme} fs={fs}
              />
            </div>
          </div>

          {/* Cohort toggle pills */}
          <div style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>
            {COHORT_ORDER.map(code => cohorts[code] ? (
              <CohortToggle key={code} code={code}
                enabled={enabledCohorts[code]} onToggle={toggleCohort}
                theme={theme} total={cohorts[code].total} fs={fs}
              />
            ) : null)}
          </div>

          {/* Day range pills */}
          <div style={{ display: "flex", gap: 3, marginBottom: 16, flexWrap: "wrap" }}>
            <Pill
              options={DAY_RANGE_OPTIONS.map(d => ({ val: d, label: `${d}d` }))}
              value={dayRange} onChange={setDayRange} theme={theme} fs={fs}
            />
          </div>

          {/* Melt overlay chart */}
          <ResponsiveContainer width="100%" height={380}>
            <ComposedChart data={visibleOverlayData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
              <CartesianGrid {...gridProps} />
              <XAxis dataKey="day" {...xAxisProps} fontSize={s(11)}
                label={{ value: "Days since hold placement", position: "insideBottom", offset: -2, fontSize: s(11), fill: theme.textMuted }}
              />
              <YAxis {...yAxisProps}
                domain={showPct ? [0, 100] : ["auto", "auto"]}
                tickFormatter={v => showPct ? `${v}%` : v}
                label={{ value: showPct ? "% Remaining" : "Holds Remaining", angle: -90, position: "insideLeft", offset: 10, fontSize: s(11), fill: theme.textMuted }}
              />
              <Tooltip content={
                <MeltTooltip showPct={showPct} theme={theme} showAvg={showAvg} priorAvg={priorAvg} />
              } />

              {/* Prior-year range band (shaded area between min and max) */}
              {showPct && showAvg && (
                <Area type="monotone" dataKey="avgRange" fill={theme.avgBand}
                  stroke="none" fillOpacity={1} isAnimationActive={false} connectNulls={false}
                />
              )}
              {/* Prior-year average line (dashed) */}
              {showPct && showAvg && (
                <Line type="monotone" dataKey="avg" stroke={theme.avgLine}
                  strokeWidth={2} strokeDasharray="6 4" dot={false}
                  connectNulls={false} isAnimationActive={false}
                />
              )}

              {/* Vertical reference line at current slider position */}
              {enabledCohorts[CURRENT_COHORT] && (
                <ReferenceLine x={effectiveSlider} stroke={theme.accent}
                  strokeDasharray="4 4" strokeOpacity={0.5}
                />
              )}
              {/* Horizontal 50% reference line */}
              {showPct && (
                <ReferenceLine y={50} stroke={theme.textDim}
                  strokeDasharray="2 6" strokeOpacity={0.35}
                />
              )}

              {/* Last clearance lines (dashed vertical per cohort) */}
              {showResolution && COHORT_ORDER.map(code => {
                const rd = resolutionDays[code];
                if (!rd || !enabledCohorts[code] || rd > dayRange) return null;
                return (
                  <ReferenceLine key={`res-${code}`} x={rd}
                    stroke={COHORT_COLORS[code]}
                    strokeDasharray="3 6" strokeOpacity={0.5} strokeWidth={1.5}
                    label={{
                      value: `${YEAR_LABELS[code] || code}: ${rd}d`,
                      position: "top", fontSize: 10, fill: COHORT_COLORS[code],
                    }}
                  />
                );
              })}

              {/* Individual cohort lines (rendered bottom-to-top so current is on top) */}
              {COHORT_ORDER.slice().reverse().map(code =>
                enabledCohorts[code] && cohorts[code] ? (
                  <Line key={code} type="stepAfter" dataKey={code}
                    stroke={COHORT_COLORS[code]}
                    strokeWidth={code === CURRENT_COHORT ? 3 : 1.8}
                    dot={false}
                    strokeOpacity={code === CURRENT_COHORT ? 1 : 0.7}
                    connectNulls={false}
                  />
                ) : null
              )}
            </ComposedChart>
          </ResponsiveContainer>

          {/* Days-to-50% summary strip */}
          {/* Shows badges per cohort for days to reach 50% and 25% remaining.
              Uses CSS grid so badges align vertically between the two rows. */}
          <div style={{
            display: "grid",
            gridTemplateColumns: `auto repeat(${COHORT_ORDER.length}, 1fr)`,
            gap: "8px 8px", marginTop: 14,
            padding: "12px 16px", background: theme.surfaceAlt, borderRadius: 8,
            alignItems: "center",
          }}>
            {/* Row 1: Days to 50% cleared */}
            <span style={{ fontSize: s(12), fontWeight: 600, color: theme.textMuted }}>
              Days to 50% cleared:
            </span>
            {COHORT_ORDER.map(code => {
              const c = cohorts[code];
              if (!c) return <span key={code} />;
              const d = c.daysTo50;
              return (
                <span key={code} style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  fontSize: s(12), fontWeight: 500, padding: "3px 8px", borderRadius: 6,
                  color: theme.text, background: `${COHORT_COLORS[code]}12`,
                  border: `1px solid ${COHORT_COLORS[code]}30`, textAlign: "center",
                }}>
                  <span style={{
                    width: 7, height: 7, borderRadius: "50%", background: COHORT_COLORS[code],
                    flexShrink: 0,
                  }} />
                  {(YEAR_LABELS[code] || code)}:
                  <span style={{
                    fontFamily: "'DM Mono',monospace", fontWeight: 700, color: COHORT_COLORS[code],
                  }}>
                    {d !== null ? `${d}d` : `>${c.curve.length - 1}d`}
                  </span>
                </span>
              );
            })}

            {/* Row 2: Days to 75% cleared */}
            <span style={{ fontSize: s(12), fontWeight: 600, color: theme.textMuted }}>
              Days to 75% cleared:
            </span>
            {COHORT_ORDER.map(code => {
              const c = cohorts[code];
              if (!c) return <span key={code} />;
              const d = c.daysTo25;
              return (
                <span key={code} style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  fontSize: s(12), fontWeight: 500, padding: "3px 8px", borderRadius: 6,
                  color: theme.text, background: `${COHORT_COLORS[code]}08`,
                  border: `1px solid ${COHORT_COLORS[code]}20`, textAlign: "center",
                }}>
                  <span style={{
                    width: 7, height: 7, borderRadius: "50%", background: COHORT_COLORS[code],
                    flexShrink: 0,
                  }} />
                  {(YEAR_LABELS[code] || code)}:
                  <span style={{
                    fontFamily: "'DM Mono',monospace", fontWeight: 700, color: COHORT_COLORS[code],
                  }}>
                    {d !== null ? `${d}d` : `>${c.curve.length - 1}d`}
                  </span>
                </span>
              );
            })}
          </div>
        </div>

        {/* ═══ DAILY CLEARANCE ═══ */}
        {/* Bar chart showing holds cleared per day for the current cohort.
            Switchable between: total (aggregate), stacked by class, or single class. */}
        <div style={{
          background: theme.surface, border: `1px solid ${theme.border}`,
          borderRadius: 12, padding: "20px 24px", marginBottom: 24,
        }}>
          <div style={{
            display: "flex", alignItems: "center", justifyContent: "space-between",
            marginBottom: 4, flexWrap: "wrap", gap: 12,
          }}>
            <div>
              <h2 style={{ fontSize: s(16), fontWeight: 700 }}>
                Daily Clearance ({YEAR_LABELS[CURRENT_COHORT]})
              </h2>
              <p style={{ fontSize: s(12), color: theme.textMuted, marginTop: 2 }}>
                Holds cleared per day. Spikes often correspond to coaching pushes, email reminders, or events.
              </p>
            </div>
            {/* View mode toggle */}
            <Pill options={[
              { val: "total", label: "Total" },
              { val: "stacked", label: "By Class" },
              { val: "FY", label: "FY" },
              { val: "SO", label: "SO" },
              { val: "JR", label: "JR" },
            ]} value={clearanceView} onChange={setClearanceView} theme={theme} fs={fs} />
          </div>

          <div style={{ marginTop: 10 }}>
            <ResponsiveContainer width="100%" height={160}>
              <BarChart data={clearanceChartData} margin={{ top: 4, right: 12, left: 0, bottom: 4 }}>
                <CartesianGrid {...gridProps} vertical={false} />
                <XAxis dataKey="dateLabel" {...xAxisProps} interval={2} />
                <YAxis {...yAxisProps} fontSize={s(10)} width={30} allowDecimals={false} />
                <Tooltip content={
                  <ClearanceTooltip theme={theme} clearanceData={clearanceChartData} />
                } />
                {/* Reference line synced to the snapshot slider */}
                {snap.date && (
                  <ReferenceLine x={fmtShort(snap.date)} stroke={theme.accent}
                    strokeWidth={1.5} strokeDasharray="4 4"
                  />
                )}

                {/* Aggregate view: single green bar per day */}
                {clearanceView === "total" && (
                  <Bar dataKey="cleared" fill={theme.sparkBar}
                    radius={[3, 3, 0, 0]} fillOpacity={0.85} maxBarSize={22}
                  />
                )}
                {/* Stacked view: FY/SO/JR layered bars */}
                {clearanceView === "stacked" && (
                  <Bar dataKey="JR" stackId="cl" fill={classColors.JR} maxBarSize={22} />
                )}
                {clearanceView === "stacked" && (
                  <Bar dataKey="SO" stackId="cl" fill={classColors.SO} maxBarSize={22} />
                )}
                {clearanceView === "stacked" && (
                  <Bar dataKey="FY" stackId="cl" fill={classColors.FY}
                    radius={[3, 3, 0, 0]} maxBarSize={22}
                  />
                )}
                {/* Single class views */}
                {clearanceView === "FY" && (
                  <Bar dataKey="FY" fill={classColors.FY}
                    radius={[3, 3, 0, 0]} fillOpacity={0.85} maxBarSize={22}
                  />
                )}
                {clearanceView === "SO" && (
                  <Bar dataKey="SO" fill={classColors.SO}
                    radius={[3, 3, 0, 0]} fillOpacity={0.85} maxBarSize={22}
                  />
                )}
                {clearanceView === "JR" && (
                  <Bar dataKey="JR" fill={classColors.JR}
                    radius={[3, 3, 0, 0]} fillOpacity={0.85} maxBarSize={22}
                  />
                )}
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Legend (shown for stacked view only, since other modes are self-evident) */}
          {clearanceView === "stacked" && (
            <div style={{
              display: "flex", justifyContent: "center", gap: 24, marginTop: 8,
              fontSize: s(12), color: theme.textMuted,
            }}>
              {[
                { k: "FY", l: "First Year" },
                { k: "SO", l: "Sophomore" },
                { k: "JR", l: "Junior" },
              ].map(({ k, l }) => (
                <div key={k} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <span style={{ width: 10, height: 10, borderRadius: 2, background: classColors[k] }} />
                  {l}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* ═══ TIME SLIDER SNAPSHOT ═══ */}
        {/* Interactive scrubber showing the current cohort's hold status on any
            given date, broken down by class standing (FY/SO/JR). */}
        <div style={{
          background: theme.surface, border: `1px solid ${theme.border}`,
          borderRadius: 12, padding: "20px 24px",
        }}>
          <div style={{
            display: "flex", alignItems: "center", justifyContent: "space-between",
            marginBottom: 8, flexWrap: "wrap", gap: 12,
          }}>
            <div>
              <h2 style={{ fontSize: s(16), fontWeight: 700 }}>
                {YEAR_LABELS[CURRENT_COHORT]} Hold Snapshot
              </h2>
              <p style={{ fontSize: s(12), color: theme.textMuted, marginTop: 2 }}>
                Scrub through time to see holds remaining by class standing.
              </p>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              {/* Area vs Bars toggle */}
              <Pill
                options={[{ val: "area", label: "Area" }, { val: "bars", label: "Bars" }]}
                value={snapMode} onChange={setSnapMode} theme={theme} fs={fs}
              />
              {/* Play / Pause / Resume animation button */}
              <button
                onClick={playing ? pauseAnimation : playAnimation}
                style={{
                  padding: "6px 18px", borderRadius: 8,
                  border: `1px solid ${theme.accent}`,
                  background: playing ? `${theme.accent}30` : `${theme.accent}18`,
                  color: theme.accent,
                  cursor: "pointer",
                  fontSize: s(13), fontWeight: 600,
                  minWidth: 130,
                }}>
                {playing ? "⏸  Pause" : isPaused ? "▶  Resume" : "▶  Play Melt"}
              </button>
            </div>
          </div>

          {/* Time slider */}
          <div style={{ marginBottom: 4, padding: "0 4px" }}>
            <div style={{
              display: "flex", justifyContent: "space-between",
              fontSize: s(13), fontWeight: 600, marginBottom: 8,
            }}>
              <span style={{ color: theme.textMuted }}>
                {snapshots[0]?.date ? fmtShort(snapshots[0].date) : ""}
              </span>
              <span style={{ color: theme.accent, fontSize: s(15) }}>
                {snap.date ? fmtLong(snap.date) : ""}
              </span>
              <span style={{ color: theme.textMuted }}>
                {snapshots.length > 0 ? fmtShort(snapshots[snapshots.length - 1].date) : ""}
              </span>
            </div>
            <input type="range" min={0} max={maxSlider} value={effectiveSlider}
              onChange={e => setSliderDay(Number(e.target.value))}
              style={{
                background: `linear-gradient(to right, ${theme.accent} ${maxSlider > 0 ? (effectiveSlider / maxSlider) * 100 : 0}%, ${theme.sliderTrack} ${maxSlider > 0 ? (effectiveSlider / maxSlider) * 100 : 0}%)`,
                accentColor: theme.accent,
              }}
            />
          </div>

          {/* Class standing breakdown cards (with total) */}
          <div style={{ display: "flex", gap: 12, marginTop: 16, marginBottom: 20, flexWrap: "wrap" }}>
            {/* Total card */}
            <div style={{
              flex: 1, minWidth: 140, padding: "14px 18px", borderRadius: 10,
              border: `1px solid ${theme.red}40`,
              background: `linear-gradient(135deg, ${theme.red}06, ${theme.red}12)`,
            }}>
              <div style={{
                fontSize: s(11), fontWeight: 600, color: theme.red,
                textTransform: "uppercase", letterSpacing: "0.06em",
              }}>Total</div>
              <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginTop: 4 }}>
                <span style={{ fontSize: s(26), fontWeight: 700, color: theme.text }}>
                  {snap.total}
                </span>
                <span style={{ fontSize: s(13), color: theme.textMuted }}>
                  / {curCohort?.total || 0}
                </span>
              </div>
              <div style={{ fontSize: s(12), color: theme.red, fontWeight: 600, marginTop: 2 }}>
                {pctCleared}% cleared
              </div>
            </div>
            {/* Per-class cards */}
            {[
              { key: "FY", label: "First Year" },
              { key: "SO", label: "Sophomore" },
              { key: "JR", label: "Junior" },
            ].map(({ key, label }) => {
              const init = snapshots[0]?.[key] || 0;
              const cur = snap[key] || 0;
              const p = init > 0 ? ((init - cur) / init * 100).toFixed(0) : 0;
              return (
                <div key={key} style={{
                  flex: 1, minWidth: 140, padding: "14px 18px", borderRadius: 10,
                  border: `1px solid ${theme.border}`,
                  background: `linear-gradient(135deg, ${classColors[key]}08, ${classColors[key]}14)`,
                }}>
                  <div style={{
                    fontSize: s(11), fontWeight: 600, color: classColors[key],
                    textTransform: "uppercase", letterSpacing: "0.06em",
                  }}>{label}</div>
                  <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginTop: 4 }}>
                    <span style={{ fontSize: s(26), fontWeight: 700, color: theme.text }}>{cur}</span>
                    <span style={{ fontSize: s(13), color: theme.textMuted }}>/ {init}</span>
                  </div>
                  <div style={{ fontSize: s(12), color: classColors[key], fontWeight: 600, marginTop: 2 }}>
                    {p}% cleared
                  </div>
                </div>
              );
            })}
          </div>

          {/* Stacked area or bar chart */}
          <ResponsiveContainer width="100%" height={260}>
            {snapMode === "area" ? (
              <AreaChart data={snapChartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
                <CartesianGrid {...gridProps} vertical={false} />
                <XAxis dataKey="date" {...xAxisProps} interval={2} />
                <YAxis {...yAxisProps}
                  label={{ value: "Holds Remaining", angle: -90, position: "insideLeft", offset: 10, fontSize: s(11), fill: theme.textMuted }}
                />
                <Tooltip content={<SnapshotTooltip theme={theme} />} />
                {snap.date && <ReferenceLine x={fmtShort(snap.date)} stroke={theme.accent} strokeWidth={2} strokeDasharray="4 4" />}
                <Area type="monotone" dataKey="JR" stackId="c" fill={classColors.JR} stroke={classColors.JR} fillOpacity={0.65} strokeWidth={0} />
                <Area type="monotone" dataKey="SO" stackId="c" fill={classColors.SO} stroke={classColors.SO} fillOpacity={0.65} strokeWidth={0} />
                <Area type="monotone" dataKey="FY" stackId="c" fill={classColors.FY} stroke={classColors.FY} fillOpacity={0.65} strokeWidth={0} />
              </AreaChart>
            ) : (
              <BarChart data={snapChartData} margin={{ top: 8, right: 12, left: 0, bottom: 4 }}>
                <CartesianGrid {...gridProps} vertical={false} />
                <XAxis dataKey="date" {...xAxisProps} interval={2} />
                <YAxis {...yAxisProps}
                  label={{ value: "Holds Remaining", angle: -90, position: "insideLeft", offset: 10, fontSize: s(11), fill: theme.textMuted }}
                />
                <Tooltip content={<SnapshotTooltip theme={theme} />} />
                {snap.date && <ReferenceLine x={fmtShort(snap.date)} stroke={theme.accent} strokeWidth={2} strokeDasharray="4 4" />}
                <Bar dataKey="JR" stackId="c" fill={classColors.JR} />
                <Bar dataKey="SO" stackId="c" fill={classColors.SO} />
                <Bar dataKey="FY" stackId="c" fill={classColors.FY} radius={[3, 3, 0, 0]} />
              </BarChart>
            )}
          </ResponsiveContainer>

          {/* Class standing legend */}
          <div style={{
            display: "flex", justifyContent: "center", gap: 24, marginTop: 12,
            fontSize: s(12), color: theme.textMuted,
          }}>
            {[
              { k: "FY", l: "First Year" },
              { k: "SO", l: "Sophomore" },
              { k: "JR", l: "Junior" },
            ].map(({ k, l }) => (
              <div key={k} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <span style={{ width: 10, height: 10, borderRadius: 2, background: classColors[k] }} />
                {l}
              </div>
            ))}
          </div>
        </div>

        {/* ═══ HOLD RECURRENCE ═══ */}
        {/* Shows how many current-cohort students are first-time vs repeat hold
            recipients. Segmented by total hold count (not class standing, since
            class is credit-based and doesn't reliably reflect years enrolled). */}
        <div style={{
          background: theme.surface, border: `1px solid ${theme.border}`,
          borderRadius: 12, padding: "20px 24px", marginTop: 24,
        }}>
          <div style={{ marginBottom: 16 }}>
            <h2 style={{ fontSize: s(16), fontWeight: 700 }}>
              Hold Recurrence ({YEAR_LABELS[CURRENT_COHORT]})
            </h2>
            <p style={{ fontSize: s(12), color: theme.textMuted, marginTop: 2 }}>
              Of {recurrenceData.total} students with holds this year, how many have been held before?
            </p>
          </div>

          {/* Horizontal stacked proportion bar */}
          <div style={{
            display: "flex", height: 32, borderRadius: 8, overflow: "hidden",
            marginBottom: 20, border: `1px solid ${theme.border}`,
          }}>
            {[1, 2, 3].map(n => {
              const g = recurrenceData.groups[n];
              const pct = recurrenceData.total > 0 ? (g.count / recurrenceData.total) * 100 : 0;
              if (pct === 0) return null;
              return (
                <div key={n} style={{
                  width: `${pct}%`, background: RECURRENCE_COLORS[n],
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: s(11), fontWeight: 700, color: "#fff",
                  minWidth: pct > 5 ? 0 : 28,
                  transition: "width 0.3s",
                }}>
                  {pct >= 8 ? `${Math.round(pct)}%` : ""}
                </div>
              );
            })}
          </div>

          {/* Three metric cards */}
          <div style={{ display: "flex", gap: 14, flexWrap: "wrap" }}>
            {[
              { n: 1, label: "1st Hold", sub: "No prior InSight holds" },
              { n: 2, label: "2nd Hold", sub: "One prior hold year" },
              { n: 3, label: "3rd Hold", sub: "Two prior hold years" },
            ].map(({ n, label, sub }) => {
              const g = recurrenceData.groups[n];
              const pct = recurrenceData.total > 0
                ? ((g.count / recurrenceData.total) * 100).toFixed(0)
                : "0";
              const clearRate = g.count > 0
                ? ((g.cleared / g.count) * 100).toFixed(0)
                : "0";
              return (
                <div key={n} style={{
                  flex: 1, minWidth: 180, padding: "16px 20px", borderRadius: 10,
                  border: `1px solid ${RECURRENCE_COLORS[n]}30`,
                  background: `linear-gradient(135deg, ${RECURRENCE_COLORS[n]}06, ${RECURRENCE_COLORS[n]}12)`,
                }}>
                  {/* Card header: colored label */}
                  <div style={{
                    display: "flex", alignItems: "center", gap: 8, marginBottom: 8,
                  }}>
                    <span style={{
                      width: 10, height: 10, borderRadius: "50%",
                      background: RECURRENCE_COLORS[n], flexShrink: 0,
                    }} />
                    <span style={{
                      fontSize: s(13), fontWeight: 700, color: RECURRENCE_COLORS[n],
                    }}>{label}</span>
                  </div>
                  {/* Count and percentage of cohort */}
                  <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
                    <span style={{
                      fontSize: s(28), fontWeight: 700, color: theme.text, lineHeight: 1.1,
                    }}>{g.count}</span>
                    <span style={{
                      fontSize: s(13), color: theme.textMuted,
                    }}>({pct}%)</span>
                  </div>
                  {/* Clearance rate */}
                  <div style={{
                    fontSize: s(12), color: theme.textMuted, marginTop: 6,
                  }}>
                    {g.cleared} cleared ({clearRate}%)
                  </div>
                  {/* Subtitle */}
                  <div style={{
                    fontSize: s(11), color: theme.textDim, marginTop: 4,
                  }}>{sub}</div>
                </div>
              );
            })}
          </div>
        </div>

        {/* ═══ FOOTER ═══ */}
        <div style={{
          textAlign: "center", padding: "20px 0 12px", fontSize: s(11), color: theme.textDim,
        }}>
          InSight Program · Champlain College Career Collaborative · All class standings included in melt curves
        </div>
      </div>
    </div>
  );
}